[package]
name = "stremio-analytics"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
stremio-core = { path="../" }
serde = "1.0.*"
serde_json = "1.0.*"
futures = "0.3.*"
enclose = "1.1.*"
derivative = "2.1.*"
