[package]
name = "stremio-state-container-web"
version = "0.1.0"
authors = ["Smart Code Ltd."]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stremio-state-ng = { git = "ssh://git@github.com/Stremio/stremio-state-ng.git" }
futures = "0.1"
wasm-bindgen = { version = "0.2.40", features = ["serde-serialize", "nightly"]  }
serde_json = "1.0.16"
serde = "1.0"
wasm-bindgen-futures = "0.3"
js-sys = "0.3"

[profile.release]
lto = true

[dependencies.web-sys]
version = "0.3.4"
features = [
	'Window',
	'Request',
	'RequestInit',
	'Response',
	'Storage'
]
