[package]
name = "stremio-core-web"
version = "0.21.0"
authors = ["Smart Code OOD"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
stremio-core = { git = "https://github.com/Stremio/stremio-core", branch = "analytics_poc" }
stremio-derive = { git = "https://github.com/Stremio/stremio-core", branch = "analytics_poc" }
serde = "1.0"
serde_json = "1.0"
url = { version = "2.2", features = ["serde"] }
percent-encoding = "2.1"
semver = { version = "0.10", features = ["serde"] }
base64 = "0.13"
either = "1.6"
flate2 = "1.0"
chrono = "0.4"
futures = "0.3"
http = "0.2"
js-sys = "0.3"
wasm-bindgen = { version = "0.2.67", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
lazy_static = "1.4"
itertools = "0.9"

[dependencies.web-sys]
version = "0.3"
features = [
	'Window',
	'Request',
	'RequestInit',
	'Response',
	'Storage',
	'console'
]
