[package]
name = "stremio-core-web"
version = "0.17.0"
authors = ["Smart Code Ltd."]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
stremio-core = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
stremio-derive = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
env-web = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
serde = "1.0"
serde_json = "1.0"
futures = "0.1"
js-sys = "0.3"
wasm-bindgen = { version = "0.2.65", features = ["serde-serialize"] }
console_error_panic_hook = "0.1"
itertools = "0.8"
