[package]
name = "stremio-core-web"
version = "0.6.0"
authors = ["Smart Code Ltd."]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stremio-core = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
stremio-derive = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
env-web = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
serde = "1.0.100"
serde_json = "1.0.40"
futures = "0.1.29"
js-sys = "0.3.27"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize", "nightly"] }
console_error_panic_hook = "0.1.6"

[profile.release]
lto = true
opt-level = 's'
