[package]
name = "stremio-core-web"
version = "0.44.8"
authors = ["Smart Code OOD"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
stremio-core = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
stremio-derive = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
stremio-analytics = { git = "https://github.com/Stremio/stremio-core", branch = "development" }
serde = "1.0.*"
serde_json = "1.0.*"
futures = "0.3.*"
http = "0.2.*"
url = { version = "2.2.*", features = ["serde"] }
chrono = "0.4.*"
semver = { version = "0.11.*", features = ["serde"] }
regex = "1.6.*"
hex = "0.4.*"
either = "1.6.*"
lazy_static = "1.4.*"
enclose = "1.1.*"
itertools = "0.10.*"
boolinator = "2.4.*"
Inflector = "0.11.*"
wasm-bindgen = { version = "=0.2.78", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.*"
console_error_panic_hook = "0.1.*"
js-sys = "0.3.*"
web-sys = { version = "0.3.*", features = [
	"WorkerGlobalScope",
	"WorkerNavigator",
	"Request",
	"RequestInit",
	"Response",
	"console",
] }
getrandom = { version = "0.2.*", features = ["js"] }
cfg-if = "0.1.*"
serde_path_to_error = "0.1.*"
