[package]
name = "stremio-derive"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1"
proc_macro_roids = "0.8"
case = "1"
