name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        eval $(ssh-agent -s)
        ssh-add
        cargo install wasm-pack && yarn build
