name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set default rust toolchain
      run: rustup default 1.64.0
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Install clippy
      run: rustup component add clippy
    - name: Lint code format
      run: cargo fmt --all -- --check
    - name: Lint code
      run: cargo clippy --all -- -D warnings
    - name: Test
      run: cargo test
    # This makes sure that core will be correctly build in release
    - name: Build in --release
      run: cargo build --release
