name: Build

on: [push]

# Stops the running workflow of previous pushes
concurrency:
  # cancel per workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Rust setup (stable)
      uses: dtolnay/rust-toolchain@stable

    - name: Lint - rustfmt
      run: cargo fmt --all -- --check

    - name: Lint - clippy
      run: cargo clippy --all --no-deps -- -D warnings

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build