name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.1.1
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Build
          run: cargo install wasm-pack && yarn build
