name: Build

on: push

# Stops the running workflow of previous pushes
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 12
  WASM_PACK_VERSION: 0.12.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu, wasm32-unknown-unknown

      - name: Lint - rustfmt
        run: cargo fmt --all -- --check

      - name: Lint - clippy
        run: cargo clippy --all --no-deps -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      # For releasing we always use stable
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack@${{ env.WASM_PACK_VERSION }}
      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run build
