name: MSRV build

on:
  # will checkout the default branch `development`
  schedule:
    # run every Friday at 17:00
    - cron: '00 17 * * 5'
  # Or ran manually
  workflow_dispatch:

# Stops the running workflow of previous pushes
concurrency:
  # cancel per workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_MSRV_VERSION: '1.67.1'

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
    - name: Rust setup (MSRV)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_MSRV_VERSION }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build