name: Release

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build
          run: rustup default nightly && cargo install wasm-pack && npm install && npm run build
        - uses: actions/setup-node@v1
          with:
            node-version: 10
            registry-url: https://registry.npmjs.org/
        - name: Publish
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            
